# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go run github.com/gobuffalo/packr/v2/packr2

builds:
- id: rare-pcre
  binary: rare-pcre
  env:
    - CGO_ENABLED=1
  flags:
    - -tags=pcre2
  ldflags:
    - -s -w
    - -X main.version={{.Version}}
    - -X main.buildSha={{.ShortCommit}}
  goarch:
    - amd64
  goos:
    - linux
- id: rare
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w
    - -X main.version={{.Version}}
    - -X main.buildSha={{.ShortCommit}}
  goarch:
    - amd64
  goos:
    - linux
    - darwin
    - windows

archives:
- allow_different_binary_count: true
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}'
    homepage: https://github.com/zix99/rare
    description: Fast, realtime regex-extraction, and aggregation into common formats such as histograms, numerical summaries, tables, and more!
    maintainer: Christopher LaPointe (chris@zdyn.net)
    license: GPLv2
    vendor: zix99
    formats:
    - deb
    - rpm

brews:
- tap:
    owner: zix99
    name: homebrew-rare
  commit_author:
    name: rare-bot
    email: noreply@zdyn.net
  homepage: https://github.com/zix99/rare
  description: Fast, realtime regex-extraction, and aggregation into common formats such as histograms, numerical summaries, tables, and more!
  test: |
    system "#{bin}/rare -v"
