name: rare

on:
  pull_request:
  push:

jobs:
  rare:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.3
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get
        run: go get -t -v ./...
      - name: Vet
        run: go vet $(go list ./... | grep -v /vendor/)
      - name: Test
        run: |
          go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: StaticCheck
        run: |
          go run honnef.co/go/tools/cmd/staticcheck ./...
      - name: Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          bash <(curl -s https://codecov.io/bash)
      - name: Pack
        run: go run github.com/gobuffalo/packr/v2/packr2
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
